spring:
  datasource:
    username: loan_tracker
    password: loan_tracker
    url: jdbc:mysql://localhost:3306/loan_tracker
   
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true 
   
  sql: 
    init:
      mode: never